# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 13:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(null=True, upload_to='photos/')),
                ('phone_number', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField(null=True)),
                ('male', models.BooleanField()),
                ('street', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=2)),
                ('zipcode', models.CharField(max_length=10)),
                ('type', models.IntegerField(choices=[('Admin', 1), ('Reviewer', 2), ('User', 3)], null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
