# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 09:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_auto_20160622_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviewer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed', models.BooleanField()),
                ('linkedin', models.URLField(null=True)),
                ('position', models.CharField(max_length=50, null=True)),
                ('current_job', models.CharField(max_length=100, null=True)),
                ('previous_job', models.CharField(max_length=100, null=True)),
                ('total_years', models.IntegerField(null=True)),
                ('bs_subject', models.CharField(max_length=50, null=True)),
                ('bs_university', models.CharField(max_length=50, null=True)),
                ('ms_subject', models.CharField(max_length=50, null=True)),
                ('ms_university', models.CharField(max_length=50, null=True)),
                ('phd_subject', models.CharField(max_length=50, null=True)),
                ('phd_university', models.CharField(max_length=50, null=True)),
                ('summary', models.CharField(max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
